services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chess_app
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./app:/var/www/html
      - ../contact:/var/www/html/contact:ro
      - ../inicio:/var/www/html/inicio:ro
      - ../jugar:/var/www/html/jugar:ro
      - ../learn:/var/www/html/learn:ro
      - ../imagenes:/var/www/html/imagenes:ro
    depends_on:
      - db
      - mailpit
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public

  db:
    image: mysql:8.0
    container_name: chess_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: chess
      MYSQL_USER: chess
      MYSQL_PASSWORD: chess
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  mailpit:
    image: axllent/mailpit:latest
    container_name: chess_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  dbdata:
